language: php

php:
  - 5.5

before_install:
   - rvm install 2.0.0
   - chmod +x travis

install:
  - composer install
  - gem install capistrano --no-ri --no-rdoc
  - gem install capistrano-symfony --no-ri --no-rdoc

script: ./travis/build.sh

after_success:

notifications:
  slack: snapcart-backend:pkOUtGSYExxS8O89fWXNHMlE