language: php

php:
  - 5.5

before_install:
   - rvm install 2.0.0

install:
  - composer install
  - gem install capistrano --no-ri --no-rdoc
  - gem install capistrano-symfony --no-ri --no-rdoc

script:
  - phpunit
  - openssl aes-256-cbc -K $encrypted_bd69831a7c24_key -iv $encrypted_bd69831a7c24_iv -in snapcarttest.pem.enc -out deployment/snapcarttest.pem -d
  - if [ printf -- '%s' "${TRAVIS_BRANCH}" | egrep -q -- "_VH" ]; then cap production deploy; fi

notifications:
  slack: snapcart-backend:pkOUtGSYExxS8O89fWXNHMlE